[
    {
        "_comment": "This configuration file contains sensitive settings that should not be accessed by unauthorized users.",
        "uriRegexs": ["^/resources.conf$"],
        "actions": [
            {
                "type": "DENY"
            }
        ]
    },
    {
        "_comment": "We dont have a favicon yet. (Avoid redirect)",
        "uriRegexs": ["^/favicon.ico$"],
        "actions": [
            {
                "type": "ACCEPT"
            }
        ]
    },
    {
        "_comment": "Hidden internal folders are denied (used only for includes).",
        "uriRegexs": ["^/includes.*$"],
        "actions": [
            {
                "type": "REDIRECT",
                "location": "/"
            }
        ]
    },
    {
        "_comment": "Execute html's as HTMLI",
        "uriRegexs": ["^/.*\\.(html|js)$", "^/$"],
        "actions": [
            { "type": "PROCESS_AS", "mode": "HTMLI" },
            { "type": "ACCEPT" }
        ]
    },
    {
        "_comment": "This resources are accessible only to logged-in users.",
        "uriRegexs": ["^/assets.*$", "^/local.*$"],
        "requireSession": false,
        "actions": [
            {
                "type": "ACCEPT"
            }
        ]
    },
    {
        "_comment": "All other requests are denied.",
        "uriRegexs": ["^.*$"],
        "actions": [
            {
                "type": "DENY"
            }
        ]
    }
]
