; Sample Configuration File for UFastAuthD3

AppVars {
    LoginPortalURL "https://login.localhost:8443"
}

; Logs
Logs {
    Debug "true"
    ShowDate "true"
    ShowColors "true"
}

; Auth
Auth {
    Driver "SQLite3"
    IAMMainFile "var/lib/ufastauthd3/main.db"
    IAMLogsFile "var/log/ufastauthd3/logs.db"
    TerminateOnSQLError "true"
}

; User Data Format
UserInfo {
;     DisplayFormat "{{USERNAME}}"
    DisplayFormat "{{FIRSTNAME}} {{LASTNAME}} - {{USERNAME}}"
}


; App Synchronization Web Server
#include "etc/ufastauthd3/web_appsync.conf"
; Auth Handler Web Server
#include "etc/ufastauthd3/web_authhandler.conf"
; Login Web Portal
#include "etc/ufastauthd3/web_portal_login.conf"
; IAM Admin Web Portal
#include "etc/ufastauthd3/web_portal_admin.conf"
; IAM User Web Portal
#include "etc/ufastauthd3/web_portal_user.conf"

