[
    {
        "_comment": "This configuration file contains sensitive settings that should not be accessed by unauthorized users.",
        "uriRegexs": ["^/resources.conf$"],
        "actions": [
            {
                "type": "DENY"
            }
        ]
    },
    {
        "_comment": "We dont have a favicon yet. (Avoid redirect)",
        "uriRegexs": ["^/favicon.ico$"],
        "actions": [
            {
                "type": "ACCEPT"
            }
        ]
    },
    {
        "_comment": "Execute html's as MantidsLang",
        "uriRegexs": ["^/.*\\.(html|js)$"],
        "actions": [
            {
                "type": "PROCESS_AS",
                "mode": "HTMLI"
            },
            {
                "_comment": "Stop processing here.",
                "type": "ACCEPT"
            }
        ]
    },
    {
        "_comment": "This resources are accessible only to logged-in users.",
        "uriRegexs": ["^/.*html$", "^/assets.*$", "^/local.*$", "^/$"],
        "requireSession": true,
        "actions": [
            {
                "type": "ACCEPT"
            }
        ]
    },
    {
        "_comment": "All other requests are denied.",
        "uriRegexs": ["^.*$"],
        "actions": [
            {
                "type": "DENY"
            }
        ]
    }
]