#pragma once

#include <json/value.h>
#include <cstdint>
#include <optional>
#include <string>

#include <Mantids30/Helpers/crypto.h>
#include <Mantids30/Helpers/encoders.h>
#include <Mantids30/Helpers/json.h>
#include <Mantids30/Helpers/random.h>

/**
 * @brief The Function enum defines the supported password hashing and authentication functions.
 *
 * The Function enum defines the supported password hashing and authentication functions. Each function is assigned a numerical value that can be used to specify the function when calling a related function.
 *
 * The available functions are:
 * - HashFunction::NOTFOUND: Not found or invalid function.
 * - HashFunction::PLAIN: Plain-text password storage (not recommended).
 * - HashFunction::SHA256: Password hashed with SHA-256 algorithm.
 * - HashFunction::SHA512: Password hashed with SHA-512 algorithm.
 * - HashFunction::SSHA256: Password hashed with salted SHA-256 algorithm.
 * - HashFunction::SSHA512: Password hashed with salted SHA-512 algorithm.
 * - HashFunction::GAUTHTIME: Time-based one-time password (TOTP) generated by Google Authenticator.
 */
enum class HashFunction : uint8_t
{
    PLAIN = 0,
    SHA256 = 1,
    SHA512 = 2,
    SSHA256 = 3,
    SSHA512 = 4,
    GAUTHTIME = 5
};

static inline std::optional<HashFunction> toHashFunction(const uint32_t &value)
{
    if (value >= 0 && value <= 5)
    {
        return static_cast<HashFunction>(value);
    }
    return std::nullopt;
}

enum class Mode : uint8_t
{
    PLAIN, // NOT RECOMMENDED.
    CHALLENGE
};

static inline Mode getAuthModeFromString(const std::string &mode)
{
    if (mode == "CHALLENGE")
    {
        return Mode::CHALLENGE;
    }
    else
    {
        return Mode::PLAIN;
    }
}

static inline std::string getStringFromAuthMode(const Mode &mode)
{
    switch (mode)
    {
    case Mode::PLAIN:
        return "PLAIN";
    case Mode::CHALLENGE:
        return "CHALLENGE";
    };
    return "PLAIN";
}

struct AuthenticationPolicy
{
    [[nodiscard]] Json::Value toJSON() const
    {
        Json::Value root;
        root["maxTries"] = maxTries;
        root["abandonedAccountExpirationSeconds"] = abandonedAccountExpirationSeconds;
        root["blockTokenTimeout"] = blockTokenTimeout;
        return root;
    }

    uint32_t maxTries = 4;
    uint32_t abandonedAccountExpirationSeconds = 180 * 24 * 3600; // 6 Months..

    // TODO: separar esto...
    uint32_t blockTokenTimeout = 7 * 24 * 3600; // 7 days..
};

struct AuthenticationSlotDetails
{
    void fromJSON(const Json::Value &j)
    {
        passwordFunction = toHashFunction(Mantids30::Helpers::JSON::ASUINT(j, "passwordFunction", 500));
        description = Mantids30::Helpers::JSON::ASSTRING(j, "description", "");
        defaultExpirationSeconds = Mantids30::Helpers::JSON::ASUINT(j, "defaultExpirationSeconds", 0);
        strengthJSONValidator = j.isMember("strengthJSONValidator") ? j["strengthJSONValidator"] : Json::nullValue;
        totp2FAStepsToleranceWindow = Mantids30::Helpers::JSON::ASUINT(j, "totp2FAStepsToleranceWindow", 0);
        canSkipWhenExpired = Mantids30::Helpers::JSON::ASBOOL(j, "canSkipWhenExpired", false);
    }

    [[nodiscard]] Json::Value toJSON() const
    {
        Json::Value jRet;
        jRet["description"] = description;
        jRet["defaultExpirationSeconds"] = defaultExpirationSeconds;
        jRet["strengthJSONValidator"] = strengthJSONValidator;
        jRet["totp2FAStepsToleranceWindow"] = totp2FAStepsToleranceWindow;
        jRet["canSkipWhenExpired"] = canSkipWhenExpired;
        if (!passwordFunction.has_value())
        {
            jRet["passwordFunction"] = 500;
        }
        else
        {
            jRet["passwordFunction"] = static_cast<uint16_t>(passwordFunction.value());
        }
        return jRet;
    }

    [[nodiscard]] bool isCompatible(const AuthenticationSlotDetails &x) const { return x.passwordFunction == passwordFunction; }

    [[nodiscard]] bool isTextPasswordFunction() const { return passwordFunction.has_value() && passwordFunction != HashFunction::GAUTHTIME; }

    AuthenticationSlotDetails(const std::string &desc, HashFunction pwdFunction, const Json::Value &strengthValidator, uint32_t defaultExpSecs, uint32_t totpToleranceWindow, bool bCanSkipWhenExpired)
        : description(desc)
        , passwordFunction(pwdFunction)
        , strengthJSONValidator(strengthValidator)
        , defaultExpirationSeconds(defaultExpSecs)
        , totp2FAStepsToleranceWindow(totpToleranceWindow)
        , canSkipWhenExpired(bCanSkipWhenExpired)
    {}

    AuthenticationSlotDetails() = default;

    std::string description;

    std::optional<HashFunction> passwordFunction = std::nullopt;
    Json::Value strengthJSONValidator;
    uint32_t defaultExpirationSeconds = 0;
    uint32_t totp2FAStepsToleranceWindow = 0;
    bool canSkipWhenExpired = false;
};

struct Credential
{
    static Credential createFromJSON(const Json::Value &j)
    {
        Credential c;
        c.fromJSON(j);
        return c;
    }

    void fromJSON(const Json::Value &j)
    {
        slotDetails.fromJSON(j["slotDetails"]);
        mustChange = Mantids30::Helpers::JSON::ASBOOL(j, "mustChange", true);
        badAttempts = Mantids30::Helpers::JSON::ASUINT(j, "badAttempts", 0);
        lastChange = static_cast<time_t>(Mantids30::Helpers::JSON::ASINT64(j, "lastChange", 0));
        expirationTimestamp = static_cast<time_t>(Mantids30::Helpers::JSON::ASINT64(j, "expirationTimestamp", 0));
        hash = Mantids30::Helpers::JSON::ASSTRING(j, "hash", "");
        Mantids30::Helpers::Encoders::fromHex(Mantids30::Helpers::JSON::ASSTRING(j, "ssalt", "FFFFFFFF"), ssalt, 4);
    }

    [[nodiscard]] Json::Value toJSON(const AuthenticationPolicy &authPolicy) const
    {
        Json::Value jRet;
        jRet["hash"] = hash;
        jRet["isLocked"] = isLocked;
        jRet["mustChange"] = mustChange;
        jRet["badAttempts"] = badAttempts;
        jRet["lastChange"] = lastChange;
        jRet["isExpired"] = isExpired();
        jRet["slotDetails"] = slotDetails.toJSON();
        jRet["expirationTimestamp"] = expirationTimestamp;
        jRet["ssalt"] = Mantids30::Helpers::Encoders::toHex(ssalt, 4);
        jRet["hasExceededMaxAttempts"] = hasExceededMaxAttempts(authPolicy);

        return jRet;
    }

    static Credential createSHA256TemporalCredential(const std::string &password)
    {
        Credential cred;
        cred.slotDetails = AuthenticationSlotDetails("SHA256 Temporal", HashFunction::SHA256, "", 0, 0, false);
        cred.hash = Mantids30::Helpers::Crypto::calcSHA256(password);
        return cred;
    }

    [[nodiscard]] Credential getPublicData(const AuthenticationPolicy &authPolicy) const
    {
        Credential credPubData = *this;
        credPubData.hash = "";
        credPubData.currentAuthPolicy = authPolicy;
        return credPubData;
    }

    [[nodiscard]] bool hasExceededMaxAttempts(const AuthenticationPolicy &authPolicy) const { return (badAttempts + 1) >= authPolicy.maxTries; }
    [[nodiscard]] bool isExpired() const { return (time(nullptr) > expirationTimestamp && expirationTimestamp != 0); }

    void setExpirationTimeAutomatically() { expirationTimestamp = 1; }

    bool isLocked = false;
    bool mustChange = true;
    uint32_t badAttempts = 0;
    // 0 means that the password does not expire... 1 means that it's expired unless and when you change the password, the expiration will be set to current time + slot default time...
    time_t expirationTimestamp = 1, lastChange = 0;
    std::string hash;
    unsigned char ssalt[4] = {0xFF, 0xFF, 0xFF, 0xFF};
    AuthenticationSlotDetails slotDetails;
    AuthenticationPolicy currentAuthPolicy;
};

enum class AuthenticationResult : uint16_t
{
    AUTHENTICATED = 0,        // AUTHENTICATED!
    INTERNAL_ERROR = 500,     // INTERNAL ERROR (OTHER)
    NOT_IMPLEMENTED = 501,    // AUTHENTICATION NOT IMPLEMENTED YET :(
    DUPLICATED_SESSION = 502, // DUPLICATED SESSION ID

    EXPIRED_CREDENTIAL = 100,         // VALID, user is just warned about.
    EXPIRED_ACCOUNT = 102,            // ACCOUNT EXPIRED. NOT USABLE
    DISABLED_ACCOUNT = 103,           // ACCOUNT DISABLED BY ADMIN.
    UNCONFIRMED_ACCOUNT = 104,        // ACCOUNT NOT CONFIRMED YET.
    INVALID_ACCOUNT = 105,            // INVALID OR NON-EXISTENT ACCOUNT
    AUTHENTICATION_FAILED = 106,      // AUTHENTICATION FAILED (Bad Password).
    CREDENTIAL_INDEX_NOT_FOUND = 107, // Authentication Slot SlotId not found.
    AUTH_SCHEME_CHANGED = 108,        // Authentication scheme changed.
    ACCOUNT_NOT_IN_APP = 109,         // Account is not registered on the application
    AUTH_SCHEME_EMPTY = 110,          // Authentication scheme is empty.
    INACTIVE_ACCOUNT = 111,           // ACCOUNT INACTIVE. NOT USABLE
    LOCKED_CREDENTIAL = 112,          // AUTHENTICATION FAILED (LOCKED CREDENTIAL).
    MUST_CHANGE_CREDENTIAL = 113,     // AUTHENTICATION OK, but CREDENTIAL NEED TO BE CHANGED NOW TO UNLOCK.

    BAD_PARAMETERS = 993, // BAD PARAMETERS.
    INVALID_DOMAIN = 994, // AUTHENTICATION FAILED.
    INVALID_AUTHENTICATOR = 995,
    SESSIONLIMITS_EXCEEDED = 996,
    ANSWER_TIMEDOUT = 997,
    EXPIRED = 998,
    UNAUTHENTICATED = 999
};

[[nodiscard]] inline bool IS_CREDENTIAL_AUTHENTICATED(AuthenticationResult result) noexcept
{
    return result == AuthenticationResult::AUTHENTICATED || result == AuthenticationResult::EXPIRED_CREDENTIAL || result == AuthenticationResult::MUST_CHANGE_CREDENTIAL;
}

[[nodiscard]] inline const char *authResultToString(AuthenticationResult result) noexcept
{
    switch (result)
    {
    case AuthenticationResult::AUTHENTICATED:
        return "Authenticated";
    case AuthenticationResult::INTERNAL_ERROR:
        return "Authentication Internal Error";
    case AuthenticationResult::NOT_IMPLEMENTED:
        return "Authentication not implemented yet";
    case AuthenticationResult::DUPLICATED_SESSION:
        return "Session ID Duplicated Error";
    case AuthenticationResult::EXPIRED_CREDENTIAL:
        return "Credential Expired";
    case AuthenticationResult::EXPIRED_ACCOUNT:
        return "Account Expired";
    case AuthenticationResult::INACTIVE_ACCOUNT:
        return "Account is inactive";
    case AuthenticationResult::DISABLED_ACCOUNT:
        return "Account Disabled";
    case AuthenticationResult::UNCONFIRMED_ACCOUNT:
        return "Account Unconfirmed";
    case AuthenticationResult::INVALID_ACCOUNT:
        return "Invalid Account";
    case AuthenticationResult::AUTHENTICATION_FAILED:
        return "Authentication Failed";
    case AuthenticationResult::LOCKED_CREDENTIAL:
        return "Credential Locked";
    case AuthenticationResult::CREDENTIAL_INDEX_NOT_FOUND:
        return "Authentication Slot ID Not Found";
    case AuthenticationResult::AUTH_SCHEME_CHANGED:
        return "Authentication Scheme Changed";
    case AuthenticationResult::ACCOUNT_NOT_IN_APP:
        return "Account not registered in the application";
    case AuthenticationResult::AUTH_SCHEME_EMPTY:
        return "Authentication Scheme is Empty";
    case AuthenticationResult::BAD_PARAMETERS:
        return "Bad Parameters";
    case AuthenticationResult::INVALID_DOMAIN:
        return "Invalid domain name";
    case AuthenticationResult::INVALID_AUTHENTICATOR:
        return "Invalid or undefined authenticator";
    case AuthenticationResult::SESSIONLIMITS_EXCEEDED:
        return "Sessions limits exceeded";
    case AuthenticationResult::ANSWER_TIMEDOUT:
        return "Answer timed out";
    case AuthenticationResult::EXPIRED:
        return "Expired authentication";
    case AuthenticationResult::UNAUTHENTICATED:
        return "Not authenticated yet";
    case AuthenticationResult::MUST_CHANGE_CREDENTIAL:
        return "Credential Authenticated and must be changed.";
    default:
        return "Unknown authentication result";
    }
}

struct AuthenticationSchemeUsedSlot
{
    AuthenticationSchemeUsedSlot(uint32_t id, uint32_t priority, bool isOptional)
        : slotId(id)
        , orderPriority(priority)
        , optional(isOptional)
    {}

    AuthenticationSchemeUsedSlot(uint32_t id, uint32_t priority, bool isOptional, const AuthenticationSlotDetails & _details)
        : slotId(id)
        , orderPriority(priority)
        , optional(isOptional)
        , details(_details)
    {}

    /**
     * @brief Converts the object to a JSON representation.
     * @return Json::Value The JSON object representing this structure.
     */
    [[nodiscard]] Json::Value toJSON() const
    {
        Json::Value r;
        r["slotId"] = slotId;
        r["orderPriority"] = orderPriority;
        r["optional"] = optional;
        r["details"] = details.toJSON();
        return r;
    }

    /**
     * @brief Populates the object from a JSON representation.
     * @param j The JSON object to populate the data from.
     * @return AuthenticationSchemeUsedSlot The populated object.
     */
    void fromJSON(const Json::Value &j)
    {
        slotId = Mantids30::Helpers::JSON::ASUINT(j, "slotId", 0);
        orderPriority = Mantids30::Helpers::JSON::ASUINT(j, "orderPriority", 0);
        optional = Mantids30::Helpers::JSON::ASBOOL(j, "optional", false);
        details.fromJSON(j["details"]);
    }

    uint32_t slotId;
    uint32_t orderPriority;
    bool optional;

    AuthenticationSlotDetails details;
};

struct RoleDetails
{
    RoleDetails() = default;
    std::string roleName;
    std::string description;
};
